Revert "qcacld-3.0: Add support to get last available vdev info"
This reverts commit 85a2421c53be23c52f4c98a31ee6641cc6dca899 and silences the following compilation errors:

../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_stats.c:6234:20: error: incomplete definition of type 'struct stats_event'
        for (i = 0; i < ev->num_summary_stats; i++) {
                        ~~^
../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_stats.c:6227:9: note: forward declaration of 'struct stats_event'
        struct stats_event *ev = stats_ev;
               ^
../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_stats.c:6237:8: error: incomplete definition of type 'struct stats_event'
                                        ev->vdev_summary_stats[i].vdev_id);
                                        ~~^
../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_stats.c:6227:9: note: forward declaration of 'struct stats_event'
        struct stats_event *ev = stats_ev;
               ^
../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_stats.c:6247:8: error: incomplete definition of type 'struct stats_event'
                                        ev->vdev_summary_stats[i].stats.rssi;
                                        ~~^
../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_stats.c:6227:9: note: forward declaration of 'struct stats_event'
        struct stats_event *ev = stats_ev;
               ^
../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_stats.c:6257:2: error: implicit declaration of function 'ucfg_mc_cp_stats_register_lost_link_info_cb' [-Werror,-Wimplicit-function-declaration]
        ucfg_mc_cp_stats_register_lost_link_info_cb(

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>